server:
  tomcat:
    threads:
      max: 200
    accept-count: 100
  port: 8443
  http2:
    enabled: true
  ssl:
    session-cache-size: 10000
    session-timeout: 1200
    enabled: true
    key-store: classpath:cert/keystore.p12
    key-store-password: your-password
    ciphers:
      - TLS_AES_256_GCM_SHA384
      - TLS_AES_128_GCM_SHA256
    enabled-protocols:
      - TLSv1.3
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@${CMS_DB_HOST}:1521/${CMS_DB_SN}
    username: ${CMS_DB_USER}
    password: ${CMS_DB_PASS}
  ucp:
    initial-pool-size: 10
    min-pool-size: 20
    max-pool-size: 30
    connection-wait-timeout: 30
    timeout-check-interval: 5
    inactive-connection-timeout: 120
    abandoned-connection-timeout: 180
    validate-connection-on-borrow: true
    max-connection-lifetime: 1800
    max-connection-reuse-count: 5000

logging:
  level:
    root: INFO
    oracle.ucp: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: metrics, health
  metrics:
    export:
      prometheus:
        enabled: true

